FROM python:3.11-slim

# Set environment variables
ENV ACTIVE_SERVERS="1 2 3"

# Copy the requirements file into the container
COPY requirements.txt /requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r /requirements.txt

# Copy the rest of the application code into the container
COPY . /

# Expose port 5001 for the load balancer application
EXPOSE 5001

# Run the load balancer application
CMD ["python", "load_balancer.py"]
